# Generated by Django 3.1.1 on 2020-09-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='origin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
