# Generated by Django 3.1.1 on 2020-09-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_monster_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='image',
            field=models.ImageField(height_field=50, null=True, upload_to=None, width_field=50),
        ),
    ]
