# Generated by Django 3.1.1 on 2020-09-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200917_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='rental',
            name='TIMEFRAME',
        ),
        migrations.AddField(
            model_name='rental',
            name='timeframe',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('N', 'Night')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='rental',
            name='date',
            field=models.DateField(verbose_name='rental date'),
        ),
    ]
