# Generated by Django 3.1.1 on 2020-09-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200917_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='monster',
            name='image',
        ),
        migrations.AddField(
            model_name='monster',
            name='extras',
            field=models.ManyToManyField(to='main_app.Extra'),
        ),
    ]
