# Generated by Django 3.1.1 on 2020-09-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200924_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
